version: '3.1'

services:
  db-customer:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-cami}
      POSTGRES_DB: ${POSTGRES_DB:-orders}
      PGDATA: /data/postgres
    volumes:
      - /data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:

volumes:
  postgres:
