CREATE TABLE pedidos
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pedidos PRIMARY KEY (id)
);