CREATE TABLE item_do_pedido
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    description VARCHAR(255),
    order_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_item_do_pedido PRIMARY KEY (id)
);

ALTER TABLE item_do_pedido
    ADD CONSTRAINT FK_ITEM_DO_PEDIDO_ON_ORDER FOREIGN KEY (order_id) REFERENCES pedidos (id);